manifest:
  remotes:
    - name: custom_zmkfirmware
      url-base: https://github.com/a-wark
  projects:
    - name: zmk
      remote: custom_zmkfirmware
      revision: custom
      import: app/west.yml
  self:
    path: config
